### ISSUE TITLE
開発中に新機能を追加するなどコーディングの延長ではない作業は Copilot Chat に聞くとよい

### ISSUE THREAD

**Issue by ayuina** [tenjoufire/GitHubCopilotUsecase#4]
# 参照するライブラリが分からない

<img width="743" alt="image" src="https://github.com/tenjoufire/GitHubCopilotUsecase/assets/1955999/c95a133b-f3e4-4a9b-ae9b-70d641b46e96">

# 追加のフレームワークを組み込む方法が分からない（Entity Framework）

<img width="721" alt="image" src="https://github.com/tenjoufire/GitHubCopilotUsecase/assets/1955999/89617a8b-58d0-4716-8200-0439e941d033">

# 追加のフレームワークを組み込む方法が分からない（Dependency Injection）

<img width="700" alt="image" src="https://github.com/tenjoufire/GitHubCopilotUsecase/assets/1955999/754462a8-e059-4f08-93f1-a7abe4da268a">

**Comment by tenjoufire** [comment]
反映済みです、ありがとうございました。
